General Accuracy Improvements
Fluvian/tpp pull request #91
Opened 2022-09-14 14:03 UTC by The1UPGuy

I've made a good amount of tweaks to make TPP a bit more accurate and match footage more. The exact changes can be found on TPPCHANGELIST.txt in the main folder, that .txt file and some commented out credits to others that helped with code should probably be removed if these changes are added to the main repo. If any questions emerge about the changes i'll be sure to answer them.

2022-09-14 14:26 UTC, The1UPGuy commented
Whoops realized I made a mistake in the change list, "Mario's movement speed is directly based on movement speed" should be "Mario's movement speed is directly based on how far the stick is held", my bad.

2022-09-16 12:49 UTC, Fluvian commented
Any reason the trees were changed?

2022-09-16 13:06 UTC, The1UPGuy commented
I've changed them because when looking at footage from multiple builds the trees always seem pretty dark in them, that darker color can be replicated by fully importing the trees from the gigaleak to SM64.
![trees](https://user-images.githubusercontent.com/75804989/190645581-a9a58c90-d03b-4457-804e-4974e0d4e58c.png)

2022-09-16 13:10 UTC, Fluvian commented
The trees are actually darker in the builds, the file you imported seems to be based off of those trees, the trees in SW were lighter, there doesn't seem to be any difference in lighting either so it's just the texture being different, which is wrong. The texture in TPP right now is the correct SW95 one.

2022-09-16 13:13 UTC, The1UPGuy commented
Oh I see. I'll revert them back to how they were in TPP.

2022-09-17 11:21 UTC, Fluvian requested changes

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario_actions_moving.c
> +                        m->pretiptimer++;
Rename `pretiptimer` to `pretipTimer` to match the other struct variable names.

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario_actions_moving.c
> +    if (m->forwardVel >= targetSpeed) { //code by Guestpiki
Fix the indentation here, use spaces and not tabs.

Also, could you remove the comment credits? I'll add them to the README.

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario_actions_cutscene.c
> +    play_sound(SOUND_MARIO_HOOHOO, m->marioObj->header.gfx.cameraToObject);
Fix the indentation here.

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario_actions_airborne.c
> +	    if (m->intendedMag > 0) {
Fix the indentations here.

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario_actions_airborne.c
> +	    if (m->intendedMag > 0) {
Fix the indentations here too.

2022-09-17 11:21 UTC, Fluvian commented on src/game/mario.c
> +s8 sTerrainSounds[7][6] = { //code by Crustian
Fix the indentation here so the "S" of the `SOUND_TERRAIN_X` matches those below it.

Also I don't mind giving credit but it's just a few value changes I would have done anyway if we found the footstep sounds.

2022-09-17 11:21 UTC, Fluvian commented on src/game/interaction.c
> +        if (m->forwardVel < 0.0f) {
Indentation again.

2022-09-17 11:21 UTC, Fluvian commented on src/game/interaction.c
> +        if (gCurrLevelNum != LEVEL_CASTLE) {
Indentation here, move the if to the same the same column as the closing bracket above the `#else` directive.

2022-09-17 11:21 UTC, Fluvian commented on src/game/interaction.c
> +    /*bully->oMoveAngleYaw = newBullyYaw;
You can just remove this entirely.

2022-09-17 11:21 UTC, Fluvian commented on src/game/behaviors/bowser_bomb.inc.c
> +       o->oVelY = 0.0f;
**BUG!**

This line will be run regardless of the if statement, if statements without brackets will only be valid for one line after it, add brackets to the if statement here. 

If the bomb smoke behaves not as intended after this change then remove the brackets again but add a line between the two and move the `o->oVelY = 0.0f;` statement 4 spaces to the left.

2022-09-17 11:21 UTC, Fluvian commented on src/game/behaviors/bowser_bomb.inc.c
> +    cur_obj_scale((f32) o->oTimer / 14.0f * 9.0 + 1.0);
Indentation again.

2022-09-17 11:21 UTC, Fluvian commented on include/types.h
> +             u8 pretiptimer;
Change this to `pretipTimer` as mentioned in the other comment.

2022-09-17 11:21 UTC, Fluvian commented on TPPCHANGELIST.txt
> +TPP CHANGES LIST:
This file can be removed as it doesn't need to be in the repository, I will use it as a commit description.

2022-09-17 11:21 UTC, Fluvian commented on levels/bowser_1/areas/1/1/model.inc.c
> +Lights1 bowser_1_f3d_material_004_lights = gdSPDefLights1(
Why is the whole level re-exported with Fast64 just to remove the fog? Just revert this, I will remove the fog myself after this pull request gets merged.

2022-09-17 11:25 UTC, Fluvian commented
If these changes are made and I make the changes I mentioned I'll release it as the second release.

2022-09-17 12:57 UTC, TorutheRedFox commented on src/game/mario_step.c
> +        m->vel[1] -= 0.0f;
yep, if you're subtracting nothing, why bother have an op for it

2022-09-17 13:01 UTC, TorutheRedFox commented on src/game/mario_actions_cutscene.c
>      if (m->actionTimer == 15) {
having brackets here isn't needed as it's a single line if statement

2022-09-17 13:03 UTC, The1UPGuy commented
Oh wait there's a few more lol, GitHub didn't show them to me

2022-09-17 13:16 UTC, The1UPGuy commented
I believe that's everything. Thanks for the feedback!

2022-09-17 13:25 UTC, merged